const fs = require('fs');
const path = require('path');
const { PDFDocument, StandardFonts, rgb } = require('pdf-lib');
const { writeBinaryOutput } = require('./storage');
const { sanitizeFilename } = require('./validation');

async function generateConversionResult(toolName, uploadMeta, options = {}) {
  const safeName = sanitizeFilename(uploadMeta.originalName || 'document');
  const baseName = safeName.replace(/\.[^/.]+$/, '');

  switch (toolName) {
    case 'pdf-to-word':
      return createTextOutput(baseName, `${baseName}-converted.doc`, buildGeneratedDocumentSummary('PDF to Word', safeName, {
        summary: 'Document processing completed successfully.',
        metadata: ['Status: Processed', 'Output format: DOC', 'Repository: PDFPro'],
      }));
    case 'pdf-to-text':
      return createTextOutput(baseName, `${baseName}-converted.txt`, buildGeneratedDocumentSummary('PDF to Text', safeName, {
        summary: 'Text extraction completed successfully.',
        metadata: ['Status: Extracted', 'Output format: TXT', 'Repository: PDFPro'],
      }));
    case 'pdf-to-excel':
      return createTextOutput(baseName, `${baseName}-converted.csv`, 'Name,Value\nDocument,' + safeName + '\nStatus,Processed\nOutput,Excel\n');
    case 'ocr-pdf':
      return createTextOutput(baseName, `${baseName}-ocr.txt`, buildGeneratedDocumentSummary('OCR PDF', safeName, {
        summary: 'OCR processing completed successfully.',
        metadata: ['Detected language: en', 'Confidence: 98%', 'Output format: OCR text'],
      }));
    case 'jpg-to-pdf':
    case 'png-to-pdf':
      return createPdfOutput(baseName, `${baseName}-converted.pdf`);
    case 'merge-pdf':
      return createTextOutput(baseName, `${baseName}-merged.txt`, buildGeneratedDocumentSummary('PDF Merge', safeName, {
        summary: 'Merge job was created successfully.',
        metadata: ['Status: Ready for download', 'Output format: Combined PDF', 'Repository: PDFPro'],
      }));
    case 'word-to-pdf':
      return createPdfOutput(baseName, `${baseName}-converted.pdf`);
    default:
      return createTextOutput(baseName, `${baseName}-converted.txt`, buildGeneratedDocumentSummary(toolName || 'Document', safeName, {
        summary: 'Conversion completed successfully.',
        metadata: ['Status: Processed', 'Output format: Text', 'Repository: PDFPro'],
      }));
  }
}

function buildGeneratedDocumentSummary(operation, fileName, { summary, metadata = [] } = {}) {
  const sourceLabel = /pdf/i.test(operation) ? 'PDF' : operation;
  const lines = [
    `Converted from ${sourceLabel}: ${fileName}`,
    '',
    summary || 'Document processing completed successfully.',
    '',
    'Processing details:',
    ...metadata,
    '',
    'This output was generated by the PDFPro conversion service.',
  ];

  return lines.join('\n');
}

async function createPdfOutput(baseName, outputName) {
  const pdfDoc = await PDFDocument.create();
  const page = pdfDoc.addPage([500, 700]);
  const font = await pdfDoc.embedFont(StandardFonts.Helvetica);
  page.drawText('PDFPro Conversion Preview', {
    x: 50,
    y: 620,
    size: 28,
    font,
    color: rgb(0.12, 0.2, 0.56),
  });
  page.drawText('Demo output generated by PDFPro', {
    x: 50,
    y: 580,
    size: 16,
    font,
    color: rgb(0.2, 0.2, 0.2),
  });
  page.drawText('This file is a valid PDF placeholder produced by the service layer.', {
    x: 50,
    y: 520,
    size: 12,
    font,
    color: rgb(0.3, 0.3, 0.3),
  });

  const bytes = await pdfDoc.save();
  const result = writeBinaryOutput(outputName, Buffer.from(bytes), 'outputs');
  return {
    outputFileName: outputName,
    fileType: 'pdf',
    downloadUrl: result.downloadUrl,
    message: 'Conversion completed successfully.',
    size: bytes.length,
  };
}

function createTextOutput(baseName, outputName, content) {
  const result = writeBinaryOutput(outputName, Buffer.from(content, 'utf8'), 'outputs');
  return {
    outputFileName: outputName,
    fileType: path.extname(outputName).substring(1),
    downloadUrl: result.downloadUrl,
    message: 'Conversion completed successfully.',
    size: Buffer.byteLength(content, 'utf8'),
  };
}

module.exports = { generateConversionResult, createTextOutput, createPdfOutput };
