const fs = require('fs');
const path = require('path');
const { PDFDocument, StandardFonts, rgb } = require('pdf-lib');
const { writeBinaryOutput } = require('./storage');
const { sanitizeFilename } = require('./validation');

async function generateConversionResult(toolName, uploadMeta, options = {}) {
  const safeName = sanitizeFilename(uploadMeta.originalName || 'document');
  const baseName = safeName.replace(/\.[^/.]+$/, '');

  switch (toolName) {
    case 'pdf-to-word':
      return createTextOutput(baseName, `${baseName}-converted.doc`, `Converted from PDF: ${safeName}\n\nThis demo conversion was generated by PDFPro.\nUse the API contract to replace this placeholder with an enterprise PDF extraction engine.`);
    case 'pdf-to-text':
      return createTextOutput(baseName, `${baseName}-converted.txt`, `Extracted text from PDF file: ${safeName}\n\nPage 1: This is sample OCR/extraction content generated for demo purposes.\nPage 2: Replace the placeholder with your production PDF text extraction pipeline.`);
    case 'pdf-to-excel':
      return createTextOutput(baseName, `${baseName}-converted.csv`, 'Name,Value\nDocument,Converted via PDFPro\nStatus,Ready\n');
    case 'ocr-pdf':
      return createTextOutput(baseName, `${baseName}-ocr.txt`, `OCR result for ${safeName}\nDetected language: en\nConfidence: 98%\nText content: Editable version generated from scanned PDF for demonstration.`);
    case 'jpg-to-pdf':
    case 'png-to-pdf':
      return createPdfOutput(baseName, `${baseName}-converted.pdf`);
    case 'merge-pdf':
      return createTextOutput(baseName, `${baseName}-merged.txt`, `Merged PDF job created successfully for ${safeName}. Upload multiple files in production to combine pages into one PDF archive.`);
    case 'word-to-pdf':
      return createPdfOutput(baseName, `${baseName}-converted.pdf`);
    default:
      return createTextOutput(baseName, `${baseName}-converted.txt`, `Conversion for ${toolName} completed successfully.`);
  }
}

async function createPdfOutput(baseName, outputName) {
  const pdfDoc = await PDFDocument.create();
  const page = pdfDoc.addPage([500, 700]);
  const font = await pdfDoc.embedFont(StandardFonts.Helvetica);
  page.drawText('PDFPro Conversion Preview', {
    x: 50,
    y: 620,
    size: 28,
    font,
    color: rgb(0.12, 0.2, 0.56),
  });
  page.drawText('Demo output generated by PDFPro', {
    x: 50,
    y: 580,
    size: 16,
    font,
    color: rgb(0.2, 0.2, 0.2),
  });
  page.drawText('This file is a valid PDF placeholder produced by the service layer.', {
    x: 50,
    y: 520,
    size: 12,
    font,
    color: rgb(0.3, 0.3, 0.3),
  });

  const bytes = await pdfDoc.save();
  const result = writeBinaryOutput(outputName, Buffer.from(bytes), 'outputs');
  return {
    outputFileName: outputName,
    fileType: 'pdf',
    downloadUrl: result.downloadUrl,
    message: 'Conversion completed successfully.',
    size: bytes.length,
  };
}

function createTextOutput(baseName, outputName, content) {
  const result = writeBinaryOutput(outputName, Buffer.from(content, 'utf8'), 'outputs');
  return {
    outputFileName: outputName,
    fileType: path.extname(outputName).substring(1),
    downloadUrl: result.downloadUrl,
    message: 'Conversion completed successfully.',
    size: Buffer.byteLength(content, 'utf8'),
  };
}

module.exports = { generateConversionResult, createTextOutput, createPdfOutput };
