CREATE TABLE IF NOT EXISTS deals(id BIGSERIAL PRIMARY KEY,name TEXT NOT NULL,brand TEXT,store TEXT NOT NULL,category TEXT NOT NULL,image_url TEXT,product_url TEXT NOT NULL,original_price NUMERIC(12,2) NOT NULL,current_price NUMERIC(12,2) NOT NULL,previous_price NUMERIC(12,2),coupon_code TEXT,coupon_min_order NUMERIC(12,2),coupon_type TEXT,expiry_at TIMESTAMPTZ,last_checked_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),verified BOOLEAN NOT NULL DEFAULT FALSE,enabled BOOLEAN NOT NULL DEFAULT TRUE,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());CREATE TABLE IF NOT EXISTS price_history(id BIGSERIAL PRIMARY KEY,deal_id BIGINT REFERENCES deals(id) ON DELETE CASCADE,price NUMERIC(12,2) NOT NULL,checked_at TIMESTAMPTZ NOT NULL DEFAULT NOW());CREATE TABLE IF NOT EXISTS notification_logs(id BIGSERIAL PRIMARY KEY,deal_id BIGINT REFERENCES deals(id) ON DELETE SET NULL,channel TEXT NOT NULL,event_type TEXT NOT NULL,status TEXT NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());CREATE INDEX IF NOT EXISTS deals_public_idx ON deals(enabled,verified);CREATE INDEX IF NOT EXISTS deals_store_idx ON deals(store);CREATE INDEX IF NOT EXISTS deals_category_idx ON deals(category);
INSERT INTO deals(name,brand,store,category,product_url,original_price,current_price,verified,enabled)
SELECT 'Gym Hound Graphic Print Men Round Neck Black T-Shirt','Gym Hound','Flipkart','Clothing','https://www.flipkart.com/mens-tshirts/pr?sid=edy',999,295,true,true WHERE NOT EXISTS (SELECT 1 FROM deals WHERE name='Gym Hound Graphic Print Men Round Neck Black T-Shirt');
INSERT INTO deals(name,brand,store,category,product_url,original_price,current_price,verified,enabled)
SELECT 'ADIDAS Self Design Men Polo Neck Grey T-Shirt','ADIDAS','Flipkart','Clothing','https://www.flipkart.com/mens-tshirts/pr?sid=edy',1799,809,true,true WHERE NOT EXISTS (SELECT 1 FROM deals WHERE name='ADIDAS Self Design Men Polo Neck Grey T-Shirt');
INSERT INTO deals(name,brand,store,category,product_url,original_price,current_price,verified,enabled)
SELECT 'RARE RABBIT Men Solid Casual Green Shirt','RARE RABBIT','Flipkart','Clothing','https://www.flipkart.com/mens-casual-shirts/pr?sid=mmk%2Ckp7',2799,1103,true,true WHERE NOT EXISTS (SELECT 1 FROM deals WHERE name='RARE RABBIT Men Solid Casual Green Shirt');

INSERT INTO deals(name,brand,store,category,product_url,original_price,current_price,verified,enabled) SELECT 'Gym Hound Men Graphic Print Round Neck Polyester Black T-Shirt','Gym Hound','Flipkart','Clothing','https://www.flipkart.com/gym-hound-graphic-print-men-round-neck-black-t-shirt/p/itm495fac5aacb2a',999,281,true,true WHERE NOT EXISTS (SELECT 1 FROM deals WHERE product_url='https://www.flipkart.com/gym-hound-graphic-print-men-round-neck-black-t-shirt/p/itm495fac5aacb2a');

INSERT INTO deals(name,brand,store,category,product_url,original_price,current_price,verified,enabled,last_checked_at)
SELECT 'EYEBOGLER Men Colour-Block Regular Fit T-Shirt','EYEBOGLER','AJIO','Clothing','https://www.ajio.com/men-tshirts/c/830216014',2499,250,true,true,NOW()
WHERE NOT EXISTS (SELECT 1 FROM deals WHERE name='EYEBOGLER Men Colour-Block Regular Fit T-Shirt' AND store='AJIO');

INSERT INTO deals(name,brand,store,category,product_url,original_price,current_price,verified,enabled,last_checked_at) SELECT 'KOSAKSI Men Washed/Ombre Typography Round Neck Black T-Shirt','KOSAKSI','Flipkart','Clothing','https://www.flipkart.com/kosaksi-washed-ombre-typography-men-round-neck-black-t-shirt/p/itm348e46d9bf1bf',899,312,true,true,NOW() WHERE NOT EXISTS (SELECT 1 FROM deals WHERE product_url='https://www.flipkart.com/kosaksi-washed-ombre-typography-men-round-neck-black-t-shirt/p/itm348e46d9bf1bf');

INSERT INTO deals(name,brand,store,category,product_url,original_price,current_price,verified,enabled,last_checked_at) SELECT 'Creation By London Hills Men Typography Round Neck Brown T-Shirt','Creation By London Hills','Flipkart','Clothing','https://www.flipkart.com/creation-london-hills-typography-men-round-neck-brown-t-shirt/p/itmaf298f5b4fab1',1299,341,true,true,NOW() WHERE NOT EXISTS (SELECT 1 FROM deals WHERE product_url='https://www.flipkart.com/creation-london-hills-typography-men-round-neck-brown-t-shirt/p/itmaf298f5b4fab1');

INSERT INTO deals(name,brand,store,category,product_url,original_price,current_price,verified,enabled,last_checked_at) SELECT 'ADIDAS Men Self Design Polo Neck Grey T-Shirt','ADIDAS','Flipkart','Clothing','https://www.flipkart.com/adidas-self-design-men-polo-neck-grey-t-shirt/p/itm90febe8ec8711',1799,1139,true,true,NOW() WHERE NOT EXISTS (SELECT 1 FROM deals WHERE product_url='https://www.flipkart.com/adidas-self-design-men-polo-neck-grey-t-shirt/p/itm90febe8ec8711');

INSERT INTO deals(name,brand,store,category,product_url,original_price,current_price,verified,enabled,last_checked_at) SELECT 'EyeBogler Men Striped Round Neck Dark Blue T-Shirt','EyeBogler','Flipkart','Clothing','https://www.flipkart.com/eyebogler-striped-men-round-neck-dark-blue-t-shirt/p/itm7cfa62dd485be',1299,256,true,true,NOW() WHERE NOT EXISTS (SELECT 1 FROM deals WHERE product_url='https://www.flipkart.com/eyebogler-striped-men-round-neck-dark-blue-t-shirt/p/itm7cfa62dd485be');

INSERT INTO deals(name,brand,store,category,product_url,original_price,current_price,verified,enabled,last_checked_at) SELECT 'EternaEssential Men Printed Round Neck Black T-Shirt','EternaEssential','Flipkart','Clothing','https://www.flipkart.com/hi/eternaessential-printed-men-round-neck-black-t-shirt/p/itm6bfc9c06d6a0c',1599,350,true,true,NOW() WHERE NOT EXISTS (SELECT 1 FROM deals WHERE product_url='https://www.flipkart.com/hi/eternaessential-printed-men-round-neck-black-t-shirt/p/itm6bfc9c06d6a0c');

INSERT INTO deals(name,brand,store,category,product_url,original_price,current_price,verified,enabled,last_checked_at) SELECT 'Flipkart SmartBuy Men Solid Round Neck Black T-Shirt','Flipkart SmartBuy','Flipkart','Clothing','https://www.flipkart.com/flipkart-smartbuy-solid-men-round-neck-black-t-shirt/p/itma0b79d016e67e',999,313,true,true,NOW() WHERE NOT EXISTS (SELECT 1 FROM deals WHERE product_url='https://www.flipkart.com/flipkart-smartbuy-solid-men-round-neck-black-t-shirt/p/itma0b79d016e67e');

INSERT INTO deals(name,brand,store,category,product_url,original_price,current_price,verified,enabled,last_checked_at) SELECT 'Alvin Men Embroidered Polo Neck Grey T-Shirt','Alvin','Flipkart','Clothing','https://www.flipkart.com/alvin-embroidered-men-polo-neck-grey-t-shirt/p/itm328829ae69cad',1400,370,true,true,NOW() WHERE NOT EXISTS (SELECT 1 FROM deals WHERE product_url='https://www.flipkart.com/alvin-embroidered-men-polo-neck-grey-t-shirt/p/itm328829ae69cad');

INSERT INTO deals(name,brand,store,category,product_url,original_price,current_price,verified,enabled,last_checked_at) SELECT 'TAZO Men Printed Polo Neck Grey T-Shirt','TAZO','Flipkart','Clothing','https://www.flipkart.com/tazo-printed-men-polo-neck-grey-t-shirt/p/itmf0ef4fe2ce340',1299,274,true,true,NOW() WHERE NOT EXISTS (SELECT 1 FROM deals WHERE product_url='https://www.flipkart.com/tazo-printed-men-polo-neck-grey-t-shirt/p/itmf0ef4fe2ce340');

INSERT INTO deals(name,brand,store,category,product_url,original_price,current_price,verified,enabled,last_checked_at) SELECT 'Buda Jeans Co Men Regular Fit Polo T-Shirt','Buda Jeans Co','AJIO','Clothing','https://www.ajio.com/buda-jeans-co-men-regular-fit-polo-t-shirt/p/703166025002',1499,390,true,true,NOW() WHERE NOT EXISTS (SELECT 1 FROM deals WHERE product_url='https://www.ajio.com/buda-jeans-co-men-regular-fit-polo-t-shirt/p/703166025002');

INSERT INTO deals(name,brand,store,category,product_url,original_price,current_price,verified,enabled,last_checked_at) SELECT 'ADIDAS Men Printed Polo Neck Polyester Blue T-Shirt','ADIDAS','Flipkart','Clothing','https://www.flipkart.com/adidas-printed-men-polo-neck-blue-t-shirt/p/itme512fd40a9896',1399,660,true,true,NOW() WHERE NOT EXISTS (SELECT 1 FROM deals WHERE product_url='https://www.flipkart.com/adidas-printed-men-polo-neck-blue-t-shirt/p/itme512fd40a9896');
