CREATE TABLE IF NOT EXISTS deals(id BIGSERIAL PRIMARY KEY,name TEXT NOT NULL,brand TEXT,store TEXT NOT NULL,category TEXT NOT NULL,image_url TEXT,product_url TEXT NOT NULL,original_price NUMERIC(12,2) NOT NULL,current_price NUMERIC(12,2) NOT NULL,previous_price NUMERIC(12,2),coupon_code TEXT,coupon_min_order NUMERIC(12,2),coupon_type TEXT,expiry_at TIMESTAMPTZ,last_checked_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),verified BOOLEAN NOT NULL DEFAULT FALSE,enabled BOOLEAN NOT NULL DEFAULT TRUE,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());CREATE TABLE IF NOT EXISTS price_history(id BIGSERIAL PRIMARY KEY,deal_id BIGINT REFERENCES deals(id) ON DELETE CASCADE,price NUMERIC(12,2) NOT NULL,checked_at TIMESTAMPTZ NOT NULL DEFAULT NOW());CREATE TABLE IF NOT EXISTS notification_logs(id BIGSERIAL PRIMARY KEY,deal_id BIGINT REFERENCES deals(id) ON DELETE SET NULL,channel TEXT NOT NULL,event_type TEXT NOT NULL,status TEXT NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());CREATE INDEX IF NOT EXISTS deals_public_idx ON deals(enabled,verified);CREATE INDEX IF NOT EXISTS deals_store_idx ON deals(store);CREATE INDEX IF NOT EXISTS deals_category_idx ON deals(category);
INSERT INTO deals(name,brand,store,category,product_url,original_price,current_price,verified,enabled)
SELECT 'KAJARU Self Design Men Zip Neck Black T-Shirt','KAJARU','Flipkart','Clothing','https://www.flipkart.com/kajaru-self-design-men-zip-neck-black-t-shirt/p/itmb14e05ec6cdca',999,270,true,true
WHERE NOT EXISTS (SELECT 1 FROM deals WHERE product_url='https://www.flipkart.com/kajaru-self-design-men-zip-neck-black-t-shirt/p/itmb14e05ec6cdca');
INSERT INTO deals(name,brand,store,category,product_url,original_price,current_price,verified,enabled)
SELECT 'Helken Men Regular Fit Dyed/Ombre Casual Shirt','Helken','Flipkart','Clothing','https://www.flipkart.com/helken-men-dyed-ombre-casual-green-shirt/p/itmb273ac4d739e2',2999,313,true,true
WHERE NOT EXISTS (SELECT 1 FROM deals WHERE product_url='https://www.flipkart.com/helken-men-dyed-ombre-casual-green-shirt/p/itmb273ac4d739e2');
INSERT INTO deals(name,brand,store,category,product_url,original_price,current_price,verified,enabled)
SELECT 'KAJARU Self Design Men Zip Neck Grey T-Shirt','KAJARU','Flipkart','Clothing','https://www.flipkart.com/kajaru-self-design-men-zip-neck-grey-t-shirt/p/itm6c56e3e1f6145',999,270,true,true
WHERE NOT EXISTS (SELECT 1 FROM deals WHERE product_url='https://www.flipkart.com/kajaru-self-design-men-zip-neck-grey-t-shirt/p/itm6c56e3e1f6145');
