require('dotenv').config();const express=require('express');const cors=require('cors');const helmet=require('helmet');const rateLimit=require('express-rate-limit');const path=require('path');const{Pool}=require('pg');const{z}=require('zod');
const app=express(),port=Number(process.env.PORT||3000),pool=new Pool({connectionString:process.env.DATABASE_URL,ssl:process.env.DATABASE_URL&&!process.env.DATABASE_URL.includes('localhost')?{rejectUnauthorized:false}:false});
app.use(helmet({contentSecurityPolicy:false}));app.use(cors({origin:true}));app.use(express.json({limit:'200kb'}));app.use(rateLimit({windowMs:60000,max:120}));
const discount=d=>Math.max(0,Math.round((1-Number(d.current_price)/Number(d.original_price))*100));const map=d=>({...d,discount_percent:discount(d),saved_amount:Math.max(0,Number(d.original_price)-Number(d.current_price))});
function admin(req,res,next){if(!process.env.ADMIN_TOKEN||req.headers.authorization!==`Bearer ${process.env.ADMIN_TOKEN}`)return res.status(401).json({error:'Unauthorized'});next()}
app.get('/health',async(req,res)=>{try{await pool.query('select 1');res.json({ok:true})}catch(e){res.status(503).json({ok:false})}});
app.get('/api/stores',(req,res)=>res.json(['Amazon India','Flipkart','Myntra','AJIO','Zepto','Flipkart Minutes','Instamart','Blinkit']));
app.get('/api/deals',async(req,res)=>{try{const q=String(req.query.q||''),store=String(req.query.store||''),category=String(req.query.category||''),min=Number(req.query.minDiscount||0),coupon=req.query.coupon==='true',sort=String(req.query.sort||'discount');const a=[],w=['enabled=true','verified=true'];if(q){a.push('%'+q+'%');w.push(`(name ILIKE $${a.length} OR brand ILIKE $${a.length} OR category ILIKE $${a.length})`)}if(store){a.push(store);w.push(`store=$${a.length}`)}if(category){a.push(category);w.push(`category=$${a.length}`)}if(min){a.push(min);w.push(`(100-current_price*100/NULLIF(original_price,0)) >= $${a.length}`)}if(coupon)w.push('coupon_code IS NOT NULL');const order={discount:'(current_price/original_price) ASC',price:'current_price ASC',savings:'(original_price-current_price) DESC',newest:'created_at DESC',ending:'expiry_at ASC NULLS LAST'}[sort]||'(current_price/original_price) ASC';const r=await pool.query(`SELECT * FROM deals WHERE ${w.join(' AND ')} ORDER BY ${order} LIMIT 100`,a);res.json(r.rows.map(map))}catch(e){res.status(500).json({error:'Unable to load deals'})}});
const schema=z.object({name:z.string().min(2),brand:z.string().optional().nullable(),store:z.enum(['Amazon India','Flipkart','Myntra','AJIO','Zepto','Flipkart Minutes','Instamart','Blinkit']),category:z.string().min(2),image_url:z.string().url().optional().nullable(),product_url:z.string().url(),original_price:z.number().positive(),current_price:z.number().positive(),previous_price:z.number().positive().optional().nullable(),coupon_code:z.string().optional().nullable(),coupon_min_order:z.number().positive().optional().nullable(),coupon_type:z.enum(['coupon','bank','sale','verified_discount','limited_time']).optional(),expiry_at:z.string().datetime().optional().nullable(),verified:z.boolean().default(false),enabled:z.boolean().default(true)});
app.post('/api/admin/deals',admin,async(req,res)=>{const p=schema.safeParse(req.body);if(!p.success)return res.status(400).json({error:p.error.flatten()});const d=p.data;if(d.current_price>=d.original_price)return res.status(400).json({error:'Deal must have a real price discount'});const r=await pool.query(`INSERT INTO deals(name,brand,store,category,image_url,product_url,original_price,current_price,previous_price,coupon_code,coupon_min_order,coupon_type,expiry_at,verified,enabled) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15) RETURNING *`,[d.name,d.brand,d.store,d.category,d.image_url,d.product_url,d.original_price,d.current_price,d.previous_price,d.coupon_code,d.coupon_min_order,d.coupon_type,d.expiry_at,d.verified,d.enabled]);await pool.query('INSERT INTO price_history(deal_id,price) VALUES($1,$2)',[r.rows[0].id,d.current_price]);res.status(201).json(map(r.rows[0]))});
app.patch('/api/admin/deals/:id',admin,async(req,res)=>{const keys=['name','brand','category','image_url','product_url','original_price','current_price','previous_price','coupon_code','coupon_min_order','coupon_type','expiry_at','verified','enabled'];const e=Object.entries(req.body).filter(([k])=>keys.includes(k));if(!e.length)return res.status(400).json({error:'No editable fields'});const set=e.map(([k],i)=>`${k}=$${i+1}`).join(','),v=e.map(([,x])=>x);v.push(req.params.id);const r=await pool.query(`UPDATE deals SET ${set},updated_at=NOW(),last_checked_at=NOW() WHERE id=$${v.length} RETURNING *`,v);if(!r.rowCount)return res.status(404).json({error:'Not found'});if(req.body.current_price!=null)await pool.query('INSERT INTO price_history(deal_id,price) VALUES($1,$2)',[req.params.id,req.body.current_price]);res.json(map(r.rows[0]))});
app.delete('/api/admin/deals/:id',admin,async(req,res)=>{await pool.query('DELETE FROM deals WHERE id=$1',[req.params.id]);res.status(204).end()});app.get('/api/admin/price-history/:id',admin,async(req,res)=>res.json((await pool.query('SELECT * FROM price_history WHERE deal_id=$1 ORDER BY checked_at DESC',[req.params.id])).rows));app.get('/api/admin/notifications',admin,async(req,res)=>res.json((await pool.query('SELECT * FROM notification_logs ORDER BY created_at DESC LIMIT 100')).rows));
app.use(express.static(path.join(__dirname,'frontend','dist')));app.get('*',(req,res)=>res.sendFile(path.join(__dirname,'frontend','dist','index.html')));app.listen(port,()=>console.log('UseToolBench Deals on '+port));