const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const { config, toolCatalog } = require('../backend/config');
const { validateFile } = require('../backend/services/validation');
const { renderPdfEditorPage } = require('../frontend/pageRenderer');
const { generateConversionResult } = require('../backend/services/conversion');

const scriptText = fs.readFileSync(path.join(__dirname, '..', 'frontend', 'public', 'script.js'), 'utf8');

test('config exposes default app settings', () => {
  assert.equal(typeof config.port, 'number');
  assert.ok(config.port > 0);
});

test('tool catalog contains PDF tools', () => {
  assert.ok(toolCatalog.length > 10);
  assert.ok(toolCatalog.some((tool) => tool.slug === 'pdf-to-word'));
  assert.ok(toolCatalog.some((tool) => tool.slug === 'ocr-pdf'));
});

test('validation rejects empty files and supports allowed extensions', () => {
  const invalid = validateFile(null, { allowedExtensions: ['.pdf'] });
  assert.equal(invalid.valid, false);

  const valid = validateFile({ originalname: 'sample.pdf', size: 1024, mimetype: 'application/pdf' }, { allowedExtensions: ['.pdf'] });
  assert.equal(valid.valid, true);
});

test('conversion UI emits a real download button on success', () => {
  assert.match(scriptText, /download=\"\$\{outputName\}\"/);
  assert.match(scriptText, /class=\"download-btn\"/);
});

test('pdf editor page is available and includes editor workspace', () => {
  const html = renderPdfEditorPage();
  assert.match(html, /PDF Editor|Edit PDF Online/i);
  assert.match(html, /Upload a PDF to start editing/i);
  assert.match(html, /Download PDF/i);
});

test('pdf conversion output omits demo placeholder text', async () => {
  const result = await generateConversionResult('pdf-to-word', { originalName: 'sample.pdf' }, {});
  const outputPath = path.join(__dirname, '..', 'storage', 'outputs', result.outputFileName);

  assert.ok(result.downloadUrl.includes('/downloads/outputs/'));
  assert.equal(result.message, 'Conversion completed successfully.');
  assert.doesNotMatch(result.downloadUrl, /demo|placeholder/i);

  const fileText = fs.readFileSync(outputPath, 'utf8');
  assert.match(fileText, /Converted from PDF: sample.pdf/i);
  assert.doesNotMatch(fileText, /This demo conversion was generated by PDFPro|placeholder/i);
});
