import { FormEvent, useEffect, useMemo, useState } from "react";
import "../styles.css";

type Deal={id:number;name:string;brand?:string;store:string;category:string;image_url?:string;product_url:string;original_price:number;current_price:number;discount_percent:number;saved_amount:number;coupon_code?:string;coupon_min_order?:number;coupon_type?:string;expiry_at?:string;last_checked_at:string};
const STORES=["All","Amazon India","Flipkart","Myntra","AJIO","Zepto","Flipkart Minutes","Instamart","Blinkit"];
const CATS=["Clothing","Shoes","Watches","Wallets","Belts","Bags","Sunglasses","Accessories","Grooming","Personal care","Perfumes","Electronics","Mobiles & accessories","Fitness","Home & office","Daily essentials"];
const money=(n:number)=>`₹${Math.round(Number(n)).toLocaleString("en-IN")}`;
const pct=(d:Deal)=>Math.round(Number(d.discount_percent)||((1-d.current_price/d.original_price)*100));
function App(){
 const [deals,setDeals]=useState<Deal[]>([]),[q,setQ]=useState(""),[store,setStore]=useState("All"),[cat,setCat]=useState(""),[min,setMin]=useState(0),[sort,setSort]=useState("discount"),[loading,setLoading]=useState(false),[error,setError]=useState("");
 const load=async()=>{setLoading(true);setError("");try{const p=new URLSearchParams();if(q)p.set("q",q);if(store!=="All")p.set("store",store);if(cat)p.set("category",cat);if(min)p.set("minDiscount",String(min));p.set("sort",sort);const r=await fetch(`/api/deals?${p}`);if(!r.ok)throw Error("API unavailable");setDeals(await r.json())}catch(e){setDeals([]);setError("Live deal feed is not connected yet. No unverified products are shown.")}finally{setLoading(false)}};
 useEffect(()=>{load()},[store,cat,min,sort]);
 const sections=useMemo(()=>({hot:deals.filter(d=>pct(d)>=50&&pct(d)<60),mega:deals.filter(d=>pct(d)>=60),coupon:deals.filter(d=>!!d.coupon_code),drops:deals.filter(d=>Number(d.previous_price)>Number(d.current_price))}),[deals]);
 const submit=(e:FormEvent)=>{e.preventDefault();load()};
 return <div className="app"><header className="top"><div className="nav"><a className="logo" href="/">DEAL<span>HUB</span></a><nav><a href="#stores">Stores</a><a href="#categories">Categories</a><a href="#coupons">Coupons</a><a href="#biggest">Biggest Discounts</a></nav><span className="verified">✓ VERIFIED DEALS ONLY</span></div><form className="search" onSubmit={submit}><span>⌕</span><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search Casio, men shoes, Titan, perfume, shirts under ₹1000…"/><button>Search</button></form></header>
 <main><section className="hero"><div><div className="eyebrow">🇮🇳 INDIA · MEN’S SHOPPING DEALS</div><h1>🔥 Best Men’s Deals <em>Today.</em></h1><p>Only discounted products, genuine coupons and real price drops. No full-price listings. No fake offers.</p><div className="hero-pills"><b>✓ Verified prices</b><b>⚡ Updated daily</b><b>🔒 Secure deal links</b></div></div><div className="hero-stat"><strong>50–60%</strong><span>OFF COUPONS</span><small>Priority deals</small></div></section>
 <section className="quick" id="biggest"><button className={min===50?"active":""} onClick={()=>setMin(50)}>🔥 50–60% OFF</button><button className={min===60?"active":""} onClick={()=>setMin(60)}>💥 60%+ OFF</button><button className={q==="coupon"?"active":""} onClick={()=>{setQ("coupon");load()}}>🎟️ Coupon Deals</button><button onClick={()=>setSort("savings")}>🏷️ Biggest Savings</button><button onClick={()=>setSort("ending")}>⏰ Ending Soon</button></section>
 <div className="layout"><aside className="filters"><div className="filter-title">FILTER DEALS <button onClick={()=>{setStore("All");setCat("");setMin(0);setQ("")}}>Reset</button></div><label>Store<select value={store} onChange={e=>setStore(e.target.value)}>{STORES.map(x=><option key={x}>{x}</option>)}</select></label><label>Category<select value={cat} onChange={e=>setCat(e.target.value)}><option value="">All categories</option>{CATS.map(x=><option key={x}>{x}</option>)}</select></label><label>Minimum discount<select value={min} onChange={e=>setMin(Number(e.target.value))}><option value={0}>Any discount</option><option value={30}>30%+</option><option value={50}>50%+</option><option value={60}>60%+</option></select></label><label>Sort<select value={sort} onChange={e=>setSort(e.target.value)}><option value="discount">Biggest discount</option><option value="price">Lowest price</option><option value="savings">Biggest savings</option><option value="newest">Newest deals</option><option value="ending">Ending soon</option></select></label><div className="category-list" id="categories"><b>Categories</b>{CATS.slice(0,10).map(x=><button key={x} onClick={()=>setCat(x)}>{x}</button>)}</div></aside>
 <section className="content"><div className="section-head"><div><div className="eyebrow">LIVE FEED</div><h2>Verified Men’s Discounts</h2><p>Every listing must have a store, product URL, current price and verification timestamp.</p></div><span>{deals.length} deals</span></div>{loading&&<div className="state">Checking verified deals…</div>}{error&&!loading&&<div className="state"><strong>No live deals displayed</strong><span>{error}</span></div>}{!loading&&!error&&deals.length===0&&<div className="state"><strong>Waiting for verified deals</strong><span>The public site stays clean until real products are verified and published.</span></div>}{deals.length>0&&<div className="grid">{deals.map(d=><DealCard d={d} key={d.id}/>)}</div>}
 <DealSection title="🔥 50–60% OFF COUPONS" items={sections.hot}/><DealSection title="💥 60%+ OFF" items={sections.mega}/><DealSection title="🎟️ COUPON DEALS" items={sections.coupon}/><DealSection title="🏷️ BIGGEST PRICE DROPS" items={sections.drops}/></section></div>
 <section className="stores" id="stores"><div className="eyebrow">SHOP BY STORE</div><h2>Deals from India’s biggest stores</h2><div>{STORES.slice(1).map(s=><button key={s} onClick={()=>setStore(s)}>{s}<span>→</span></button>)}</div></section></main>
 <footer><div className="logo">DEAL<span>HUB</span></div><p>Men’s discounts only. Approved APIs, feeds and legally permitted sources only.</p><p>© 2026 DealHub India · No fake discounts · No fake coupon codes</p></footer></div>
}
function DealCard({d}:{d:Deal}){const p=pct(d);return <article className="deal-card">{d.image_url?<img src={d.image_url} alt={d.name} loading="lazy"/>:<div className="image-placeholder">DEAL<br/><b>{p}% OFF</b></div>}<div className="deal-body"><div className="deal-top"><span className="badge">🔥 {p}% OFF</span><span className="store">{d.store}</span></div><h3>{d.name}</h3><p className="brand">{d.brand||"Men’s product"} · <b>✓ Verified Deal</b></p><div className="price"><s>{money(d.original_price)}</s><strong>{money(d.current_price)}</strong><span>Save {money(d.saved_amount)}</span></div>{d.coupon_code&&<div className="coupon">🎟️ <b>{d.coupon_code}</b>{d.coupon_min_order&&<small>Min. order {money(d.coupon_min_order)}</small>}</div>}<div className="meta"><span>Checked {new Date(d.last_checked_at).toLocaleString("en-IN",{dateStyle:"medium",timeStyle:"short"})}</span>{d.expiry_at&&<span>Ends {new Date(d.expiry_at).toLocaleDateString("en-IN")}</span>}</div><a className="deal-button" href={d.product_url} target="_blank" rel="noopener noreferrer sponsored">VIEW DEAL ↗</a></div></article>}
function DealSection({title,items}:{title:string;items:Deal[]}){if(!items.length)return null;return <section className="mini-section" id="coupons"><div className="section-head"><h2>{title}</h2></div><div className="grid">{items.slice(0,4).map(d=><DealCard d={d} key={d.id}/>)}</div></section>}
export default App;