import { FormEvent, useEffect, useMemo, useState } from "react";
import "../styles.css";

type Deal={id:number;name:string;brand?:string;store:string;category:string;image_url?:string;product_url:string;original_price:number;current_price:number;discount_percent:number;saved_amount:number;coupon_code?:string;coupon_min_order?:number;coupon_type?:string;expiry_at?:string;last_checked_at:string;previous_price?:number};
const STORES=["All","Amazon India","Flipkart","Myntra","AJIO","Zepto","Flipkart Minutes","Instamart","Blinkit"];
const CATS=["Clothing","Shoes","Watches","Wallets","Belts","Bags","Sunglasses","Accessories","Grooming","Personal care","Perfumes","Electronics","Mobiles & accessories","Fitness","Home & office","Daily essentials"];
const FALLBACK_DEALS:Deal[]=[
{id:1,name:"KOSAKSI Men Washed/Ombre Typography Round Neck Black T-Shirt",brand:"KOSAKSI",store:"Flipkart",category:"Clothing",product_url:"https://www.flipkart.com/kosaksi-washed-ombre-typography-men-round-neck-black-t-shirt/p/itm348e46d9bf1bf",original_price:899,current_price:312,discount_percent:65,saved_amount:587,last_checked_at:new Date().toISOString()},
{id:2,name:"Creation By London Hills Men Typography Round Neck Brown T-Shirt",brand:"Creation By London Hills",store:"Flipkart",category:"Clothing",product_url:"https://www.flipkart.com/creation-london-hills-typography-men-round-neck-brown-t-shirt/p/itmaf298f5b4fab1",original_price:1299,current_price:341,discount_percent:74,saved_amount:958,last_checked_at:new Date().toISOString()},
{id:3,name:"ADIDAS Men Self Design Polo Neck Grey T-Shirt",brand:"ADIDAS",store:"Flipkart",category:"Clothing",product_url:"https://www.flipkart.com/adidas-self-design-men-polo-neck-grey-t-shirt/p/itm90febe8ec8711",original_price:1799,current_price:1139,discount_percent:37,saved_amount:660,last_checked_at:new Date().toISOString()},
{id:4,name:"EyeBogler Men Striped Round Neck Dark Blue T-Shirt",brand:"EyeBogler",store:"Flipkart",category:"Clothing",product_url:"https://www.flipkart.com/eyebogler-striped-men-round-neck-dark-blue-t-shirt/p/itm7cfa62dd485be",original_price:1299,current_price:256,discount_percent:80,saved_amount:1043,last_checked_at:new Date().toISOString()},
{id:5,name:"EternaEssential Men Printed Round Neck Black T-Shirt",brand:"EternaEssential",store:"Flipkart",category:"Clothing",product_url:"https://www.flipkart.com/hi/eternaessential-printed-men-round-neck-black-t-shirt/p/itm6bfc9c06d6a0c",original_price:1599,current_price:350,discount_percent:78,saved_amount:1249,last_checked_at:new Date().toISOString()},
{id:6,name:"Flipkart SmartBuy Men Solid Round Neck Black T-Shirt",brand:"Flipkart SmartBuy",store:"Flipkart",category:"Clothing",product_url:"https://www.flipkart.com/flipkart-smartbuy-solid-men-round-neck-black-t-shirt/p/itma0b79d016e67e",original_price:999,current_price:313,discount_percent:69,saved_amount:686,last_checked_at:new Date().toISOString()},
{id:7,name:"Alvin Men Embroidered Polo Neck Grey T-Shirt",brand:"Alvin",store:"Flipkart",category:"Clothing",product_url:"https://www.flipkart.com/alvin-embroidered-men-polo-neck-grey-t-shirt/p/itm328829ae69cad",original_price:1400,current_price:370,discount_percent:74,saved_amount:1030,last_checked_at:new Date().toISOString()},
{id:8,name:"TAZO Men Printed Polo Neck Grey T-Shirt",brand:"TAZO",store:"Flipkart",category:"Clothing",product_url:"https://www.flipkart.com/tazo-printed-men-polo-neck-grey-t-shirt/p/itmf0ef4fe2ce340",original_price:1299,current_price:274,discount_percent:79,saved_amount:1025,last_checked_at:new Date().toISOString()},
{id:9,name:"Buda Jeans Co Men Regular Fit Polo T-Shirt",brand:"Buda Jeans Co",store:"AJIO",category:"Clothing",product_url:"https://www.ajio.com/buda-jeans-co-men-regular-fit-polo-t-shirt/p/703166025002",original_price:1499,current_price:390,discount_percent:74,saved_amount:1109,last_checked_at:new Date().toISOString()},
{id:10,name:"ADIDAS Men Printed Polo Neck Polyester Blue T-Shirt",brand:"ADIDAS",store:"Flipkart",category:"Clothing",product_url:"https://www.flipkart.com/adidas-printed-men-polo-neck-blue-t-shirt/p/itme512fd40a9896",original_price:1399,current_price:660,discount_percent:53,saved_amount:739,last_checked_at:new Date().toISOString()}
];
const money=(n:number)=>`₹${Math.round(Number(n)).toLocaleString("en-IN")}`;
const pct=(d:Deal)=>Math.round(Number(d.discount_percent)||((1-d.current_price/d.original_price)*100));
function App(){
 const [deals,setDeals]=useState<Deal[]>(FALLBACK_DEALS),[q,setQ]=useState(""),[store,setStore]=useState("All"),[cat,setCat]=useState(""),[min,setMin]=useState(0),[sort,setSort]=useState("discount"),[loading,setLoading]=useState(false),[error,setError]=useState("");
 const load=async()=>{setLoading(true);setError("");try{const p=new URLSearchParams();if(q)p.set("q",q);if(store!=="All")p.set("store",store);if(cat)p.set("category",cat);if(min)p.set("minDiscount",String(min));p.set("sort",sort);const r=await fetch(`/api/deals?${p}`);if(!r.ok)throw Error("API unavailable");setDeals(await r.json())}catch(e){setDeals(FALLBACK_DEALS);setError("Live feed unavailable; showing the verified starter deals.")}finally{setLoading(false)}};
 useEffect(()=>{load()},[store,cat,min,sort]);
 const sections=useMemo(()=>({hot:deals.filter(d=>pct(d)>=50&&pct(d)<60),mega:deals.filter(d=>pct(d)>=60),coupon:deals.filter(d=>!!d.coupon_code),drops:deals.filter(d=>Number(d.previous_price)>Number(d.current_price))}),[deals]);
 const submit=(e:FormEvent)=>{e.preventDefault();load()};
 return <div className="app"><header className="top"><div className="nav"><a className="logo" href="/">DEAL<span>HUB</span></a><nav><a href="#stores">Stores</a><a href="#categories">Categories</a><a href="#coupons">Coupons</a><a href="#biggest">Biggest Discounts</a></nav><span className="verified">✓ VERIFIED DEALS ONLY</span></div><form className="search" onSubmit={submit}><span>⌕</span><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search Casio, men shoes, Titan, perfume, shirts under ₹1000…"/><button>Search</button></form></header>
 <main><section className="hero"><div><div className="eyebrow">🇮🇳 INDIA · MEN’S SHOPPING DEALS</div><h1>🔥 Best Men’s Deals <em>Today.</em></h1><p>Only discounted products, genuine coupons and real price drops. No full-price listings. No fake offers.</p><div className="hero-pills"><b>✓ Verified prices</b><b>⚡ Updated daily</b><b>🔒 Secure deal links</b></div></div><div className="hero-stat"><strong>50–60%</strong><span>OFF COUPONS</span><small>Priority deals</small></div></section>
 <section className="quick" id="biggest"><button className={min===50?"active":""} onClick={()=>setMin(50)}>🔥 50–60% OFF</button><button className={min===60?"active":""} onClick={()=>setMin(60)}>💥 60%+ OFF</button><button className={q==="coupon"?"active":""} onClick={()=>{setQ("coupon");load()}}>🎟️ Coupon Deals</button><button onClick={()=>setSort("savings")}>🏷️ Biggest Savings</button><button onClick={()=>setSort("ending")}>⏰ Ending Soon</button></section>
 <div className="layout"><aside className="filters"><div className="filter-title">FILTER DEALS <button onClick={()=>{setStore("All");setCat("");setMin(0);setQ("")}}>Reset</button></div><label>Store<select value={store} onChange={e=>setStore(e.target.value)}>{STORES.map(x=><option key={x}>{x}</option>)}</select></label><label>Category<select value={cat} onChange={e=>setCat(e.target.value)}><option value="">All categories</option>{CATS.map(x=><option key={x}>{x}</option>)}</select></label><label>Minimum discount<select value={min} onChange={e=>setMin(Number(e.target.value))}><option value={10}>10%+</option><option value={20}>20%+</option><option value={30}>30%+</option><option value={50}>50%+</option><option value={60}>60%+</option></select></label><label>Sort<select value={sort} onChange={e=>setSort(e.target.value)}><option value="discount">Biggest discount</option><option value="price">Lowest price</option><option value="savings">Biggest savings</option><option value="newest">Newest deals</option><option value="ending">Ending soon</option></select></label><div className="category-list" id="categories"><b>Categories</b>{CATS.slice(0,10).map(x=><button key={x} onClick={()=>setCat(x)}>{x}</button>)}</div></aside>
 <section className="content"><div className="section-head"><div><div className="eyebrow">LIVE FEED</div><h2>Verified Men’s Discounts</h2><p>Every listing must have a store, product URL, current price and verification timestamp.</p></div><span>{deals.length} deals</span></div>{loading&&<div className="state">Checking verified deals…</div>}{error&&!loading&&<div className="state"><strong>No live deals displayed</strong><span>{error}</span></div>}{!loading&&!error&&deals.length===0&&<div className="state"><strong>Waiting for verified deals</strong><span>The public site stays clean until real products are verified and published.</span></div>}{deals.length>0&&<div className="grid">{deals.map(d=><DealCard d={d} key={d.id}/>)}</div>}
 <DealSection title="🔥 50–60% OFF COUPONS" items={sections.hot}/><DealSection title="💥 60%+ OFF" items={sections.mega}/><DealSection title="🎟️ COUPON DEALS" items={sections.coupon}/><DealSection title="🏷️ BIGGEST PRICE DROPS" items={sections.drops}/></section></div>
 <section className="stores" id="stores"><div className="eyebrow">SHOP BY STORE</div><h2>Deals from India’s biggest stores</h2><div>{STORES.slice(1).map(s=><button key={s} onClick={()=>setStore(s)}>{s}<span>→</span></button>)}</div></section></main>
 <footer><div className="logo">DEAL<span>HUB</span></div><p>Men’s discounts only. Approved APIs, feeds and legally permitted sources only.</p><p>© 2026 DealHub India · No fake discounts · No fake coupon codes</p></footer></div>
}
function DealCard({d}:{d:Deal}){const p=pct(d);return <article className="deal-card">{d.image_url?<img src={d.image_url} alt={d.name} loading="lazy"/>:<div className="image-placeholder">DEAL<br/><b>{p}% OFF</b></div>}<div className="deal-body"><div className="deal-top"><span className="badge">🔥 {p}% OFF</span><span className="store">{d.store}</span></div><h3>{d.name}</h3><p className="brand">{d.brand||"Men’s product"} · <b>✓ Verified Deal</b></p><div className="price"><s>{money(d.original_price)}</s><strong>{money(d.current_price)}</strong><span>Save {money(d.saved_amount)}</span></div>{d.coupon_code&&<div className="coupon">🎟️ <b>{d.coupon_code}</b>{d.coupon_min_order&&<small>Min. order {money(d.coupon_min_order)}</small>}</div>}<div className="meta"><span>Checked {new Date(d.last_checked_at).toLocaleString("en-IN",{dateStyle:"medium",timeStyle:"short"})}</span>{d.expiry_at&&<span>Ends {new Date(d.expiry_at).toLocaleDateString("en-IN")}</span>}</div><a className="deal-button" href={d.product_url} target="_blank" rel="noopener noreferrer sponsored">VIEW DEAL ↗</a></div></article>}
function DealSection({title,items}:{title:string;items:Deal[]}){if(!items.length)return null;return <section className="mini-section" id="coupons"><div className="section-head"><h2>{title}</h2></div><div className="grid">{items.slice(0,4).map(d=><DealCard d={d} key={d.id}/>)}</div></section>}
export default function RootApp(){return window.location.pathname.endsWith('/admin')?<Admin/>:<App/>;}
function Admin(){const [token,setToken]=useState(""),[msg,setMsg]=useState(""),[form,setForm]=useState({name:"",brand:"",store:"Amazon India",category:"Watches",product_url:"",image_url:"",original_price:"",current_price:"",coupon_code:"",expiry_at:""});const change=(k:string,v:string)=>setForm({...form,[k]:v});const save=async()=>{setMsg("Saving…");try{const body={...form,original_price:Number(form.original_price),current_price:Number(form.current_price),verified:true,enabled:true};const r=await fetch(`/api/admin/deals`,{method:"POST",headers:{"Content-Type":"application/json",Authorization:"Bearer "+token},body:JSON.stringify(body)});setMsg(r.ok?"✓ Verified deal published":"Error: "+(await r.text()))}catch(e){setMsg("Backend unavailable")}};return <div className="admin"><header className="top"><div className="nav"><a className="logo" href="/">DEAL<span>HUB</span></a><a href="/">← Public site</a></div></header><main><div className="section-head"><div><div className="eyebrow">OWNER DASHBOARD</div><h2>Deal verification & publishing</h2><p>Only publish products after checking the store price and offer.</p></div></div><div className="admin-card"><label>Admin token<input type="password" value={token} onChange={e=>setToken(e.target.value)} placeholder="ADMIN_TOKEN"/></label><div className="admin-grid">{Object.entries(form).map(([k,v])=><label key={k}>{k.replace(/_/g," ")}<input value={v} onChange={e=>change(k,e.target.value)} placeholder={k}/></label>)}</div><button className="admin-save" onClick={save}>VERIFY & PUBLISH DEAL</button><p>{msg}</p></div></main></div>}
